import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Braces, ChevronDown, CircleDot, Clock3, Code2, Command, Copy, Database, ExternalLink, FileSearch, GitFork, Moon, Network, Play, RefreshCw, Search, Settings, Sparkles, Sun, Terminal, Zap } from 'lucide-react';
import type { CrmContext, SavedEnvironment, ToolMessage } from '../../shared/types';
import { Recorder } from './Recorder';
import './style.css';
type View = 'console' | 'traces' | 'tools' | 'settings' | 'recorder';
const tabs = [{id:'console', label:'API Console', icon:Terminal},{id:'traces',label:'Trace Logs',icon:FileSearch},{id:'tools',label:'Tools',icon:Sparkles}] as const;
type TraceLog = { plugintracelogid: string; typename?: string; messageblock?: string; exceptiondetails?: string; performanceexecutionduration?: number; createdon?: string; mode?: number };
function App(){
 const [view,setView]=useState<View>('console'),[ctx,setCtx]=useState<CrmContext>({connected:false}),[method,setMethod]=useState('GET'),[path,setPath]=useState('/api/data/v9.2/accounts?$select=name,revenue&$top=10'),[response,setResponse]=useState(''),[running,setRunning]=useState(false),[dark,setDark]=useState(false),[copied,setCopied]=useState(false),[logs,setLogs]=useState<TraceLog[]>([]),[traceError,setTraceError]=useState(''),[traceLoading,setTraceLoading]=useState(false),[environments,setEnvironments]=useState<SavedEnvironment[]>([]);
 useEffect(()=>{browser.runtime.sendMessage({type:'GET_ACTIVE_CONTEXT'} satisfies ToolMessage).then(v=>v&&setCtx(v)).catch(()=>{});browser.storage.local.get(['themeEnabled','environments']).then(x=>{setDark(Boolean(x.themeEnabled));setEnvironments((x.environments as SavedEnvironment[])||[])});},[]);
 const run=async()=>{setRunning(true);setResponse('');try{const [tab]=await browser.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw Error('No active Dynamics tab');const result=await browser.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',args:[method,path],func:async(m,p)=>{const r=await fetch(p,{method:m,headers:{Accept:'application/json','Content-Type':'application/json; charset=utf-8','OData-MaxVersion':'4.0','OData-Version':'4.0'}});return{status:r.status,body:await r.text()}}});const out=result[0]?.result;let body=out?.body||'{}';try{body=JSON.stringify(JSON.parse(body),null,2)}catch{}setResponse(`HTTP ${out?.status}\n\n${body}`)}catch(e){setResponse(`Request failed\n${String(e)}`)}finally{setRunning(false)}};
 const copy=()=>{navigator.clipboard.writeText([ctx.recordId,ctx.entityName,ctx.formName].filter(Boolean).join('\n'));setCopied(true);setTimeout(()=>setCopied(false),1200)};
 const theme=async()=>{const next=!dark;setDark(next);await browser.storage.local.set({themeEnabled:next});await browser.runtime.sendMessage({type:'SET_THEME',enabled:next} satisfies ToolMessage).catch(()=>{})};
 const loadTraces=async()=>{setTraceLoading(true);setTraceError('');try{const [tab]=await browser.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw Error('No active Dynamics tab');const request='/api/data/v9.2/plugintracelogs?$select=plugintracelogid,typename,messageblock,exceptiondetails,performanceexecutionduration,createdon,mode&$orderby=createdon desc&$top=25';const result=await browser.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',args:[request],func:async p=>{const r=await fetch(p,{headers:{Accept:'application/json','OData-MaxVersion':'4.0','OData-Version':'4.0'}});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}});setLogs(result[0]?.result?.value||[])}catch(e){setTraceError(String(e))}finally{setTraceLoading(false)}};
 const addEnvironment=async()=>{const url=window.prompt('Dynamics environment URL (https://org.crm.dynamics.com)');if(!url)return;try{const parsed=new URL(url);if(parsed.protocol!=='https:'||!parsed.hostname.endsWith('.dynamics.com'))throw Error();const name=window.prompt('Environment name',parsed.hostname.split('.')[0])||parsed.hostname;const next=[...environments,{id:crypto.randomUUID(),name,url:parsed.origin,kind:'Dev' as const,color:'#43db9b'}];setEnvironments(next);await browser.storage.local.set({environments:next})}catch{window.alert('Enter a valid HTTPS dynamics.com URL')}};
 const switchEnvironment=async(env:SavedEnvironment)=>{const [tab]=await browser.tabs.query({active:true,currentWindow:true});if(!tab?.id)return;const target=new URL('/main.aspx',env.url);if(ctx.entityName)target.searchParams.set('etn',ctx.entityName);if(ctx.recordId){target.searchParams.set('pagetype','entityrecord');target.searchParams.set('id',ctx.recordId)}await browser.tabs.update(tab.id,{url:target.toString()})};
 useEffect(()=>{if(view==='traces'&&!logs.length&&!traceLoading)void loadTraces()},[view]);
 if(view==='recorder')return <Recorder context={ctx} onClose={()=>setView('tools')}/>;
 return <div className="app"><header><div className="brand"><div className="logo"><Braces/></div><div><b>Dynamics Toolkit</b><span>Developer companion</span></div></div><div><button className="icon" onClick={theme}>{dark?<Moon/>:<Sun/>}</button><button className="icon" onClick={()=>setView('settings')}><Settings/></button></div></header>
 <section className="environment"><div className="env"><i/><div><span>CURRENT ENVIRONMENT</span><b>{ctx.orgName||'Contoso Development'}</b></div><ChevronDown/></div><em>DEV</em></section>
 <section className="record"><div className="record-icon"><Database/></div><div className="record-text"><span>{ctx.entityName||'account'}</span><b>{ctx.recordName||'Northwind Traders'}</b><small>{ctx.recordId||'8d3f4c21-93b6-ee11-a569-000d3a8b1c2d'}</small></div><button onClick={copy}><Copy/>{copied?'Copied':'Copy context'}</button></section>
 <nav>{tabs.map(t=><button key={t.id} className={view===t.id?'active':''} onClick={()=>setView(t.id)}><t.icon/>{t.label}</button>)}</nav><main>
 {view==='console'&&<><Title title="Web API Console" text="Run requests against the current organization"><button className="sub"><Clock3/>History</button></Title><div className="request"><select value={method} onChange={e=>setMethod(e.target.value)}><option>GET</option><option>POST</option><option>PATCH</option><option>DELETE</option></select><input value={path} onChange={e=>setPath(e.target.value)}/><button onClick={run} disabled={running}><Play/>{running?'Running':'Run'}</button></div><div className="builder"><div><label>QUERY BUILDER</label><button><Code2/>FetchXML</button></div><section><button><b>$select</b><span>name, revenue</span></button><button><b>$filter</b><span>Add filter</span></button><button><b>$expand</b><span>Add relation</span></button></section></div><div className="response"><div><label>RESPONSE</label>{response&&<em>200 OK</em>}</div><pre>{response||'{\n  "ready": true,\n  "message": "Run a request to see results"\n}'}</pre></div></>}
 {view==='traces'&&<><Title title="Plugin Trace Logs" text="Latest executions from this organization"><button className="sub" onClick={loadTraces} disabled={traceLoading}><RefreshCw className={traceLoading?'spin':''}/>{traceLoading?'Loading':'Refresh'}</button></Title><div className="filters"><Search/><input placeholder="Search message or plugin…"/><button>Latest 25 <ChevronDown/></button></div>{traceError&&<div className="notice error">{traceError}</div>}{!traceLoading&&!traceError&&!logs.length&&<div className="notice">No plugin trace logs found. Check tracing settings and privileges.</div>}<div className="logs">{logs.map(x=>{const failed=Boolean(x.exceptiondetails);return <article key={x.plugintracelogid} title={x.exceptiondetails||x.messageblock}><i className={failed?'exception':'success'}/><div><span>{failed?'Exception':'Success'} · {x.createdon?new Date(x.createdon).toLocaleString():'Unknown time'}</span><b>{x.typename||'Plugin execution'}</b></div><small>{x.performanceexecutionduration??0} ms</small><ExternalLink/></article>})}</div></>}
 {view==='tools'&&<><Title title="Developer Tools" text="Inspect, debug, and navigate faster"/><div className="tools">{[[Command,'Command palette','Jump to tables, views, forms and flows','⌘ ⇧ K'],[CircleDot,'Dirty fields','Highlight values changed on this form','Active'],[Activity,'Form performance','Resources and execution timeline','1.24 s'],[Network,'Relationship map','Explore N:N and 1:N relationships','Open'],[GitFork,'Repro recorder','Capture annotated steps for a ticket','Record'],[Zap,'Metadata inspector','Hover fields for schema details','Active']].map(([Icon,a,b,c]:any)=><button key={a} onClick={()=>a==='Repro recorder'&&setView('recorder')}><div><Icon/></div><section><b>{a}</b><span>{b}</span></section><em>{c}</em></button>)}</div></>}
 {view==='settings'&&<><Title title="Settings" text="Customize your Toolkit experience"/><div className="settings"><h3>Environments</h3>{environments.map(env=><button className="setting" key={env.id} onClick={()=>switchEnvironment(env)}><div><i style={{background:env.color}}/><span><b>{env.name}</b><small>{new URL(env.url).hostname}</small></span></div><em>{env.kind}</em></button>)}{!environments.length&&<div className="notice">No environments saved yet.</div>}<button className="add" onClick={addEnvironment}>+ Add environment</button></div></>}
 </main><footer><span><CircleDot/>{ctx.connected?'Connected to Dynamics 365':'Preview mode · Open Dynamics 365'}</span><span>v0.1.0</span></footer></div>
}
function Title({title,text,children}:{title:string,text:string,children?:React.ReactNode}){return <div className="title"><div><h2>{title}</h2><p>{text}</p></div>{children}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
