import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Braces, ChevronDown, CircleDot, Clock3, Code2, Command, Copy, Database, ExternalLink, FileSearch, GitFork, Moon, Network, Play, Plus, RefreshCw, Search, Settings, Sparkles, Square, Sun, Terminal, Trash2, Zap } from 'lucide-react';
import type { CrmContext, RequestHistoryItem, SavedEnvironment, ToolMessage, WebApiHeader, WebApiMethod, WebApiRequest, WebApiResponse } from '../../shared/types';
import './style.css';

type View = 'console' | 'traces' | 'tools' | 'settings';
type TraceLog = { plugintracelogid: string; typename?: string; messageblock?: string; exceptiondetails?: string; performanceexecutionduration?: number; createdon?: string };
const tabs = [{id:'console',label:'API Console',icon:Terminal},{id:'traces',label:'Trace Logs',icon:FileSearch},{id:'tools',label:'Tools',icon:Sparkles}] as const;
const bodyMethods: WebApiMethod[] = ['POST','PATCH','PUT'];
const emptyHeader = (): WebApiHeader => ({name:'',value:''});
const describeError = (error: unknown) => error instanceof Error ? error.message : String(error);

function App(){
 const [view,setView]=useState<View>('console'),[ctx,setCtx]=useState<CrmContext>({connected:false}),[method,setMethod]=useState<WebApiMethod>('GET');
 const [path,setPath]=useState('/api/data/v9.2/accounts'),[body,setBody]=useState(`{\n  \n}`),[headers,setHeaders]=useState<WebApiHeader[]>([]);
 const [select,setSelect]=useState('name,revenue'),[filter,setFilter]=useState(''),[expand,setExpand]=useState(''),[orderby,setOrderby]=useState(''),[top,setTop]=useState('10');
 const [fetchMode,setFetchMode]=useState(false),[fetchXml,setFetchXml]=useState('<fetch top="10"><entity name="account"><attribute name="name" /></entity></fetch>');
 const [response,setResponse]=useState(''),[responseMeta,setResponseMeta]=useState<WebApiResponse|null>(null),[error,setError]=useState(''),[running,setRunning]=useState(false);
 const [history,setHistory]=useState<RequestHistoryItem[]>([]),[showHistory,setShowHistory]=useState(false),[dark,setDark]=useState(false),[copied,setCopied]=useState(false),[logs,setLogs]=useState<TraceLog[]>([]),[traceError,setTraceError]=useState(''),[traceLoading,setTraceLoading]=useState(false),[environments,setEnvironments]=useState<SavedEnvironment[]>([]);
 const requestId=useRef<string | undefined>(undefined);
 useEffect(()=>{browser.runtime.sendMessage({type:'GET_ACTIVE_CONTEXT'} satisfies ToolMessage).then(v=>v&&setCtx(v)).catch(()=>{});browser.storage.local.get(['themeEnabled','environments','requestHistory']).then(x=>{setDark(Boolean(x.themeEnabled));setEnvironments((x.environments as SavedEnvironment[])||[]);setHistory((x.requestHistory as RequestHistoryItem[])||[])});},[]);
 const requestPath=useMemo(()=>{const [base,rawQuery='']=path.split('?',2);const params=new URLSearchParams(rawQuery);['$select','$filter','$expand','$orderby','$top','fetchXml'].forEach(key=>params.delete(key));if(fetchMode){if(fetchXml.trim())params.set('fetchXml',fetchXml.trim())}else{if(select.trim())params.set('$select',select.trim());if(filter.trim())params.set('$filter',filter.trim());if(expand.trim())params.set('$expand',expand.trim());if(orderby.trim())params.set('$orderby',orderby.trim());if(top.trim())params.set('$top',top.trim())}const query=params.toString();return `${base}${query?`?${query}`:''}`},[path,fetchMode,fetchXml,select,filter,expand,orderby,top]);
 const sendRequest=(request:WebApiRequest)=>browser.runtime.sendMessage({type:'RUN_REQUEST',request} satisfies ToolMessage) as Promise<WebApiResponse>;
 const saveHistory=async(item:RequestHistoryItem)=>{const next=[item,...history.filter(x=>x.id!==item.id)].slice(0,50);setHistory(next);await browser.storage.local.set({requestHistory:next})};
 const run=async()=>{if(method==='DELETE'&&!window.confirm(`Delete using ${requestPath}? This action may be irreversible.`))return;setError('');setResponse('');setResponseMeta(null);if(bodyMethods.includes(method)){try{JSON.parse(body)}catch(e){setError(`Invalid JSON body: ${describeError(e)}`);return}}const id=crypto.randomUUID();requestId.current=id;setRunning(true);const cleanHeaders=headers.filter(x=>x.name.trim());const item:RequestHistoryItem={id,timestamp:Date.now(),method,path:requestPath,body:bodyMethods.includes(method)?body:undefined,headers:cleanHeaders};try{const out=await sendRequest({requestId:id,method,path:requestPath,body:bodyMethods.includes(method)?body:undefined,headers:cleanHeaders});setResponseMeta(out);if(out.body){try{setResponse(JSON.stringify(JSON.parse(out.body),null,2))}catch{setResponse(out.body)}}else setResponse('(empty response body)');await saveHistory({...item,status:out.status,statusText:out.statusText})}catch(e){const message=describeError(e);setError(message.includes('AbortError')||message.toLowerCase().includes('aborted')?'Request cancelled.':`Network request failed: ${message}`);await saveHistory(item)}finally{requestId.current=undefined;setRunning(false)}};
 const cancel=async()=>{if(!requestId.current)return;await browser.runtime.sendMessage({type:'CANCEL_REQUEST',requestId:requestId.current} satisfies ToolMessage).catch(()=>{});setError('Request cancelled.');setRunning(false)};
 const restore=(item:RequestHistoryItem)=>{const [base,query='']=item.path.split('?',2);const params=new URLSearchParams(query);const savedFetchXml=params.get('fetchXml');setMethod(item.method);setPath(base||'');setBody(item.body||'{\n  \n}');setHeaders(item.headers);setFetchMode(savedFetchXml!==null);setFetchXml(savedFetchXml||'');setSelect(params.get('$select')||'');setFilter(params.get('$filter')||'');setExpand(params.get('$expand')||'');setOrderby(params.get('$orderby')||'');setTop(params.get('$top')||'');setShowHistory(false)};
 const copy=()=>{navigator.clipboard.writeText([ctx.recordId,ctx.entityName,ctx.formName].filter(Boolean).join('\n'));setCopied(true);setTimeout(()=>setCopied(false),1200)};
 const theme=async()=>{const next=!dark;setDark(next);await browser.storage.local.set({themeEnabled:next});await browser.runtime.sendMessage({type:'SET_THEME',enabled:next} satisfies ToolMessage).catch(()=>{})};
 const loadTraces=async()=>{setTraceLoading(true);setTraceError('');try{const out=await sendRequest({requestId:crypto.randomUUID(),method:'GET',path:'/api/data/v9.2/plugintracelogs?$select=plugintracelogid,typename,messageblock,exceptiondetails,performanceexecutionduration,createdon,mode&$orderby=createdon desc&$top=25'});if(out.status<200||out.status>=300)throw Error(`${out.status} ${out.statusText}`);setLogs(JSON.parse(out.body).value||[])}catch(e){setTraceError(describeError(e))}finally{setTraceLoading(false)}};
 const addEnvironment=async()=>{const url=window.prompt('Dynamics environment URL (https://org.crm.dynamics.com)');if(!url)return;try{const parsed=new URL(url);if(parsed.protocol!=='https:'||!parsed.hostname.endsWith('.dynamics.com'))throw Error();const name=window.prompt('Environment name',parsed.hostname.split('.')[0])||parsed.hostname;const next=[...environments,{id:crypto.randomUUID(),name,url:parsed.origin,kind:'Dev' as const,color:'#43db9b'}];setEnvironments(next);await browser.storage.local.set({environments:next})}catch{window.alert('Enter a valid HTTPS dynamics.com URL')}};
 const switchEnvironment=async(env:SavedEnvironment)=>{const [tab]=await browser.tabs.query({active:true,currentWindow:true});if(!tab?.id)return;const target=new URL('/main.aspx',env.url);if(ctx.entityName)target.searchParams.set('etn',ctx.entityName);if(ctx.recordId){target.searchParams.set('pagetype','entityrecord');target.searchParams.set('id',ctx.recordId)}await browser.tabs.update(tab.id,{url:target.toString()})};
 useEffect(()=>{if(view==='traces'&&!logs.length&&!traceLoading)void loadTraces()},[view]);
 return <div className="app"><header><div className="brand"><div className="logo"><Braces/></div><div><b>Dynamics Toolkit</b><span>Developer companion</span></div></div><div><button className="icon" onClick={theme}>{dark?<Moon/>:<Sun/>}</button><button className="icon" onClick={()=>setView('settings')}><Settings/></button></div></header>
 <section className="environment"><div className="env"><i/><div><span>CURRENT ENVIRONMENT</span><b>{ctx.orgName||'Contoso Development'}</b></div><ChevronDown/></div><em>DEV</em></section>
 <section className="record"><div className="record-icon"><Database/></div><div className="record-text"><span>{ctx.entityName||'account'}</span><b>{ctx.recordName||'Northwind Traders'}</b><small>{ctx.recordId||'No active record'}</small></div><button onClick={copy}><Copy/>{copied?'Copied':'Copy context'}</button></section>
 <nav>{tabs.map(t=><button key={t.id} className={view===t.id?'active':''} onClick={()=>setView(t.id)}><t.icon/>{t.label}</button>)}</nav><main>
 {view==='console'&&<><Title title="Web API Console" text="Run authenticated requests through the Dynamics bridge"><button className="sub" onClick={()=>setShowHistory(!showHistory)}><Clock3/>History ({history.length})</button></Title>
 {showHistory&&<div className="history">{history.length?history.map(item=><button key={item.id} onClick={()=>restore(item)}><b>{item.method}</b><span>{item.path}</span><em>{item.status?`${item.status} ${item.statusText}`:'Failed'} · {new Date(item.timestamp).toLocaleString()}</em></button>):<div className="notice">No requests yet.</div>}</div>}
 <div className="request"><select value={method} onChange={e=>setMethod(e.target.value as WebApiMethod)}>{['GET','POST','PATCH','PUT','DELETE'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Web API path" value={path} onChange={e=>setPath(e.target.value)}/>{running?<button className="cancel" onClick={cancel}><Square/>Stop</button>:<button onClick={run}><Play/>Run</button>}</div>
 <div className="builder"><div><label>QUERY BUILDER</label><button className={fetchMode?'active':''} onClick={()=>setFetchMode(!fetchMode)}><Code2/>{fetchMode?'OData mode':'FetchXML'}</button></div>{fetchMode?<textarea aria-label="FetchXML" value={fetchXml} onChange={e=>setFetchXml(e.target.value)}/>:<section className="query-fields">{[['$select',select,setSelect],['$filter',filter,setFilter],['$expand',expand,setExpand],['$orderby',orderby,setOrderby],['$top',top,setTop]].map(([label,value,setter])=><label key={label as string}><b>{label as string}</b><input value={value as string} onChange={e=>(setter as React.Dispatch<React.SetStateAction<string>>)(e.target.value)} placeholder={`Add ${String(label).slice(1)}`}/></label>)}</section>}<small className="resolved">{requestPath}</small></div>
 {bodyMethods.includes(method)&&<div className="editor"><label>JSON BODY</label><textarea value={body} onChange={e=>setBody(e.target.value)} spellCheck={false}/></div>}
 <div className="editor headers"><div><label>ADDITIONAL HEADERS</label><button onClick={()=>setHeaders([...headers,emptyHeader()])}><Plus/>Add</button></div>{headers.map((header,index)=><section key={index}><input placeholder="Header name" value={header.name} onChange={e=>setHeaders(headers.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/><input placeholder="Value" value={header.value} onChange={e=>setHeaders(headers.map((x,i)=>i===index?{...x,value:e.target.value}:x))}/><button aria-label="Remove header" onClick={()=>setHeaders(headers.filter((_,i)=>i!==index))}><Trash2/></button></section>)}</div>
 {error&&<div className="notice error">{error}</div>}<div className="response"><div><label>RESPONSE</label>{responseMeta&&<em className={responseMeta.status>=400?'bad':''}>{responseMeta.status} {responseMeta.statusText||'(no status text)'}</em>}</div><pre>{response||'{\n  "ready": true,\n  "message": "Run a request to see results"\n}'}</pre></div></>}
 {view==='traces'&&<><Title title="Plugin Trace Logs" text="Latest executions from this organization"><button className="sub" onClick={loadTraces} disabled={traceLoading}><RefreshCw className={traceLoading?'spin':''}/>{traceLoading?'Loading':'Refresh'}</button></Title><div className="filters"><Search/><input placeholder="Search message or plugin…"/><button>Latest 25 <ChevronDown/></button></div>{traceError&&<div className="notice error">{traceError}</div>}<div className="logs">{logs.map(x=><article key={x.plugintracelogid}><i className={x.exceptiondetails?'exception':'success'}/><div><span>{x.exceptiondetails?'Exception':'Success'} · {x.createdon?new Date(x.createdon).toLocaleString():'Unknown time'}</span><b>{x.typename||'Plugin execution'}</b></div><small>{x.performanceexecutionduration??0} ms</small><ExternalLink/></article>)}</div></>}
 {view==='tools'&&<><Title title="Developer Tools" text="Inspect, debug, and navigate faster"/><div className="tools">{[[Command,'Command palette','Jump to tables, views, forms and flows','⌘ ⇧ K'],[CircleDot,'Dirty fields','Highlight values changed on this form','Active'],[Activity,'Form performance','Resources and execution timeline','1.24 s'],[Network,'Relationship map','Explore N:N and 1:N relationships','Open'],[GitFork,'Repro recorder','Capture annotated steps for a ticket','Record'],[Zap,'Metadata inspector','Hover fields for schema details','Active']].map(([Icon,a,b,c]:any)=><button key={a}><div><Icon/></div><section><b>{a}</b><span>{b}</span></section><em>{c}</em></button>)}</div></>}
 {view==='settings'&&<><Title title="Settings" text="Customize your Toolkit experience"/><div className="settings"><h3>Environments</h3>{environments.map(env=><button className="setting" key={env.id} onClick={()=>switchEnvironment(env)}><div><i style={{background:env.color}}/><span><b>{env.name}</b><small>{new URL(env.url).hostname}</small></span></div><em>{env.kind}</em></button>)}{!environments.length&&<div className="notice">No environments saved yet.</div>}<button className="add" onClick={addEnvironment}>+ Add environment</button></div></>}
 </main><footer><span><CircleDot/>{ctx.connected?'Connected to Dynamics 365':'Open Dynamics 365 to connect'}</span><span>v0.1.0</span></footer></div>
}
function Title({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <div className="title"><div><h2>{title}</h2><p>{text}</p></div>{children}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
